name: Juce App CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt install -y cmake ninja-build gcc-11 libasound2-dev libgl-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -GNinja ..

      - name: Compile
        run: ninja

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt install -y cmake ninja-build gcc-11 libasound2-dev libgl-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -GNinja ..
          ninja

      - name: Compile
        run: ninja test

